# Generated by Django 5.2.8 on 2025-11-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_expense_user_alter_sales_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_mtd',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK TRANSFER', 'Bank Transfer'), ('DEBIT CARD', 'Debit Card')], default='CASH', max_length=20),
        ),
    ]
