# Generated by Django 5.2.8 on 2025-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_sales_payment_mtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('MARKETING', 'Marketing'), ('SUPPLIES', 'Supplies'), ('LOGISTICS', 'Logistics'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
